### PR TITLE
RMC-134 Ad Hoc Fulfilment Request Consistency

### PR DESCRIPTION
**Pull request by AdamHawtin**
# Motivation and Context
When we generate a UAC/QID pair through the case API we need to tell case processor about it so that it can update it's records and send out the event message so the UAC/QID's actually become usable downstream. This PR makes case API send a message on a direct exchange which case processor will listen to, containing the UAC, QID and case ID they are linked to. The message format mimics the event library messages but with an event type which is internal to RM only.

# What has changed
* Add rabbit configuration
* Build and send RM_UAC_CREATED event to direct exchange
* Added unit and integration tests

# How to test?
Build and run with linked case processor and acceptance test branches

# Links
https://trello.com/c/AOdYVaz0/1004-rmc-134b2-eventual-consistency-for-uac-qid-creation-in-case-processor-and-case-api-part-3-8
https://github.com/ONSdigital/census-rm-case-processor/pull/40
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/103

### CODE REVIEW

**Comment by AdamHawtin** [comment]
[RMC-134(B2) eventual consistency for UAC/QID creation in case processor and case api (part 3) (8)](https://trello.com/c/AOdYVaz0/1004-rmc-134b2-eventual-consistency-for-uac-qid-creation-in-case-processor-and-case-api-part-3-8)

**Review by LukeLoze1 — APPROVED** [review]

**Review by NickGrantX — CHANGES_REQUESTED** [review]
There's no need to have a massive message with a `PayloadDTO` and a `UacQidCreatedEventDTO`. We can just send a really basic message from the Case API to Case Processor.

**Comment by AdamHawtin** [comment]
@NickGrantONS When we were tasking it we decided to use the same message construction to keep some consistency, and since we're logging it like all the other events

**Review by NickGrantX — APPROVED** [review]
The heavyweight message format is OK... not an issue. Would prefer to use small lightweight messages, but this will be fine 👍

**Pull request merged**
